### ISSUE TITLE
Finalise 3D assets

### ISSUE THREAD

**Issue by jj248** [jj248/RealmsInExile#559]
**Portraits:**

- [x] Cull excess 3D clothing assets (largely excess EPE, including Vineguard helm for #347).
- [x] Finalise portrait modifiers. (including adding elven headgear and Juke's Bellakar tweaks)
- [x] Finalise hair / beard sets (particularly Elven hairstyle selection - game rule?).
- [x] Review accessory deformers to avoid clipping.
- [x] Remove duplicate 'no hair' in Barbershop.
- [x] Change default clothing to orc-wear.
- [x] Give uruk berserkers their loincloths. (#318)
- [x] Fix issues with broken patterns and textures (e.g. feathers and the band on Ray's crown and Gandalf's hat for #641).
- [x] Ensure all assets are fully localised (#93).
- [x] Create female versions of male headgear.
- [x] Elves can get fat and thin.
- [x] Elven children at age zero look adult.
- [x] Final pass of Sketchfab for potential additions, particularly for elves.
- [x] Add DLC triggers to new Bellakarean Headgears (bellakari_commoners, bellakari_counts, bellakari_dukes)

**Props and Artifacts:**

- [ ] Gandalf's staff (model implemented, not setup in code)
- [x] Amducious' 3D model of Gondorian sword as default sword (in court, duels, for standard sword artifacts and for marshals) for Dunedain culture group
- [x] Owl's 3D model for Herugrim (item) for Hadorim
- [x] Amducious' 3D model of Morgul blade associated to its artifact
- [x] Clifford's Mirror of Galadriel model does not show up in game, something must be wrong with the asset
- [x] Didnotexpectthat's 3D model of Elven sword as default sword for Elven cultures https://discord.com/channels/751097183448727552/751336315521597482/1039568218903293974

**Map objects and holdings:**

- [x] Review map objects
- [x] Review holding gfx

**Comment by jj248** [comment]
Game option for elven hair pool?

**Comment by BriceLeduc** [comment]
Amducious, Owl, Didnotexpectthat and Clifford have made 3D assets that have not yet been added to the game.

What needs to be done :

 

- [ ] Amducious' 3D model of Gondorian sword as default sword (in court, duels, for standard sword artifacts and for marshals) for Dunedain culture group
- [ ] Owl's 3D model for Herugrim (idem) for Hadorim
- [ ] Amducious' 3D model of Morgul blade associated to its artifact
- [ ] Amducious' 3D model for Vasa associated to its artifact (https://discord.com/channels/751097183448727552/751097925509185666/953177077547417640)
- [ ]  Amducious' 3D model of marble pedestals for Gondorian courts (https://discord.com/channels/751097183448727552/751097925509185666/953065751328202762) (not sure we still have the model)
- [ ] Amducious' 3D model of the Black Chair associated to its artifact (https://discord.com/channels/751097183448727552/751097925509185666/955171353638604861) (not sure we still have the model)
- [ ] Clifford's 3D models of evil thrones (https://discord.com/channels/751097183448727552/751097925509185666/962203774963822612)
- [ ] Didnotexpectthat's 3D model of Elven sword as default sword for Elven cultures https://discord.com/channels/751097183448727552/751336315521597482/1039568218903293974

**Comment by jj248** [comment]
Gandalf also has a shiny hat that needs fixing.

**Comment by jj248** [comment]
Also ensure appropriate list of elven hairstyles.

**Comment by jj248** [comment]
Change default clothing to Uruk Clothing.

**Comment by jj248** [comment]
Give uruk berserkers their loincloths.

**Comment by JukeJukestar** [comment]
Opened an issue #789 listing many oddities/bugs I encountered.

If possible, try to sort the barbershop clothes / headgear before release so they are in a good order that makes it easy to find things

**Comment by JukeJukestar** [comment]
- [ ] Add the Bellakarean Royal Sagums (1 and 2) to be used by Bellakarean Emperors. (male_byzantine_imperial_sagum_01 and male_byzantine_imperial_sagum_02)

**Comment by BriceLeduc** [comment]
Aren't we closing this issue a little fast ? None of the new artifacts are in yet

**Comment by BriceLeduc** [comment]
I've laid the groundwork for integrating new weapon assets : created the folders and renamed the files. However it looks like the morgul blade and the gondorian sword don't show up in game, and the rohan sword is held upside down, so there's more work to be done before it's finalised
![image](https://user-images.githubusercontent.com/98077354/233955017-c8f02326-4750-403b-8bed-5804f0895e40.png)

**Comment by BriceLeduc** [comment]
I've set up the ASSET file to recognize the weapon meshes here : 
https://github.com/jj248/RealmsInExile/commit/162aa39494ba259ce60fcf25de41bbf7011b578e

All that's needed now it to convert the .fbx files into .mesh ones, and getting the elven sword files in the right format

**Comment by Jaco-Daan** [comment]
Moving to 4.0

**Comment by jj248** [comment]
Done - closing.
