### ISSUE TITLE
Dune Sea Faith/History Rework

### ISSUE THREAD

**Issue by JukeJukestar** [jj248/RealmsInExile#890]
See active suggestion thread.

## Scorpion Cult Faith
A people apart, desert deity represented by a giant scorpion takes prominence over Nadi-Manye.
Will replace Garaudan and Sanbaizani as the largest religious power.
Dominates the central dune sea, with the Goat-Cult taking prominence in the southwestern drylands/deserts of the Aukag and Qarsag. Sanbaiz will become a much smaller faith centered around a duchy in the northeastern dune sea.

# Sanbaiz Rework
Female preference minor spider cult centered around witches and thieves. Only present in eastern dune sea.

## ToDo
- [x] Make the faith
- [x] New tenet(s)
- [ ] Overhaul of Gauradan, Sanbaizani
- [ ] Overhaul Dune Sea History to reflect changes
- [ ] Scorpion-based faith icon

**Comment by JukeJukestar** [comment]
Pushing to 4.0

**Comment by jj248** [comment]
Related to #942 - closing.
